# remapping the Ctrl B key
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# reloading this file fairly easily
bind r source-file ~/.tmux.conf \; display-message "Reloaded ~/.tmux.conf"

# To be able to use my vim color in Grace cluster. This is for tmux 2.7.
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm*:Tc"

# switch panes with Option/Alt + arrows (no prefix)
bind -n M-Left  select-pane -L
bind -n M-Down  select-pane -D
bind -n M-Up    select-pane -U
bind -n M-Right select-pane -R

# resize panes with Option/Alt + Shift + arrows (no prefix)
bind -n M-S-Left  resize-pane -L
bind -n M-S-Down  resize-pane -D
bind -n M-S-Up    resize-pane -U
bind -n M-S-Right resize-pane -R

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %


